use std::{
	collections::HashSet,
	env, fs,
	path::{Path, PathBuf},
};

use proc_macro::TokenStream;
use quote::quote;

/// Embed the calling crate's locale files into the binary at compile time.
///
/// Scans `<crate_root>/locale/<lang>/LC_MESSAGES/<crate_name>.mo` for every compiled `.mo` file and registers them with the patois global registry via the `inventory` crate. Call once at module level in a library crate.
///
/// The locale directory and `.mo` files must exist at compile time. Typically
/// this means generating them in a `build.rs` that emits `cargo:rerun-if-changed=locale`.
#[proc_macro]
pub fn embed_domain(_input: TokenStream) -> TokenStream {
	let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set during macro expansion");
	let pkg_name = env::var("CARGO_PKG_NAME").expect("CARGO_PKG_NAME not set during macro expansion");
	let locale_dir = Path::new(&manifest_dir).join("locale");
	let mut file_entries = vec![];
	if locale_dir.exists() {
		if let Ok(entries) = fs::read_dir(&locale_dir) {
			let mut locales: Vec<_> = entries.flatten().collect();
			locales.sort_by_key(|e| e.file_name());
			for entry in locales {
				let locale_name = entry.file_name().to_string_lossy().to_string();
				let mo_path = entry.path().join("LC_MESSAGES").join(format!("{pkg_name}.mo"));
				if mo_path.exists() {
					let mo_path_str = mo_path.to_string_lossy().to_string();
					file_entries.push(quote! {
						(#locale_name, { const B: &[u8] = include_bytes!(#mo_path_str); B })
					});
				}
			}
		}
	}
	quote! {
		::patois::inventory::submit! {
			::patois::EmbeddedDomain {
				name: env!("CARGO_PKG_NAME"),
				files: &[ #(#file_entries),* ],
			}
		}
	}
	.into()
}

/// Embed wxWidgets' own standard message catalogs (`wxstd`) for whichever languages this
/// crate already ships — i.e. present under `<crate_root>/locale/`, the same directory
/// [`embed_domain!`] reads. Call once at module level in an app crate that depends on
/// `patois` with the `ui` feature and on `wxdragon` directly.
///
/// wxWidgets ships translations for its own built-in UI strings ("OK", "Cancel",
/// progress-dialog labels, etc.) as gettext `.mo` files, produced by the `wxdragon-sys`
/// build into `<target>/<profile>/wxdragon_sys_cmake_build/share/locale/`. There's no such
/// tree next to an installed app, so this bundles the catalogs at compile time (mirroring
/// how [`embed_domain!`] bundles the app's own translations) and expands to a
/// `WxStdCatalogLoader` type implementing `wxdragon::translations::TranslationsLoader` that
/// serves the embedded bytes on demand.
///
/// Only languages the app itself ships are embedded, so the two translation sets stay in
/// lockstep and the binary isn't bloated with wx catalogs for languages the app isn't
/// translated into. Degrades gracefully to an empty catalog set (no panic) if the wx locale
/// directory doesn't exist yet, e.g. building in CI without gettext (`msgfmt`) available at
/// wxWidgets build time.
#[proc_macro]
pub fn embed_wx_translations(_input: TokenStream) -> TokenStream {
	let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set during macro expansion");
	let app_langs = shipped_languages(Path::new(&manifest_dir));
	let mut catalogs: Vec<(String, PathBuf)> = Vec::new();
	if let Some(locale_dir) = wx_locale_dir() {
		catalogs = matching_wx_catalogs(&locale_dir, &app_langs);
	}
	let file_entries = catalogs.iter().map(|(lang, mo_path)| {
		let mo_path_str = mo_path.to_string_lossy().to_string();
		quote! { (#lang, { const B: &[u8] = include_bytes!(#mo_path_str); B }) }
	});
	quote! {
		/// A `TranslationsLoader` that serves wxWidgets' own embedded `wxstd` catalogs.
		///
		/// Generated by `patois::embed_wx_translations!()`. Zero-sized, so a fresh
		/// instance can be handed to every `Translations` object without cost.
		pub struct WxStdCatalogLoader;

		impl WxStdCatalogLoader {
			const CATALOGS: &'static [(&'static str, &'static [u8])] = &[ #(#file_entries),* ];

			/// wxWidgets requests the versioned domain (`wxstd-3.3`) first and falls back
			/// to the unversioned `wxstd`. Match both so this stays correct across wx versions.
			fn is_wxstd_domain(domain: &str) -> bool {
				domain == "wxstd" || domain.starts_with("wxstd-")
			}
		}

		impl ::wxdragon::translations::TranslationsLoader for WxStdCatalogLoader {
			fn load_catalog(&self, domain: &str, lang: &str) -> ::std::option::Option<::std::borrow::Cow<'_, [u8]>> {
				if !Self::is_wxstd_domain(domain) {
					return None;
				}
				Self::CATALOGS.iter().find(|(l, _)| *l == lang).map(|(_, bytes)| ::std::borrow::Cow::Borrowed(*bytes))
			}

			fn available_translations(&self, domain: &str) -> ::std::vec::Vec<::std::string::String> {
				if !Self::is_wxstd_domain(domain) {
					return ::std::vec::Vec::new();
				}
				Self::CATALOGS.iter().map(|(l, _)| l.to_string()).collect()
			}
		}
	}
	.into()
}

/// Languages the calling crate ships, as lowercased directory names from `<manifest_dir>/locale/`.
fn shipped_languages(manifest_dir: &Path) -> HashSet<String> {
	let locale_dir = manifest_dir.join("locale");
	let mut langs = HashSet::new();
	if let Ok(entries) = fs::read_dir(&locale_dir) {
		for entry in entries.flatten() {
			if entry.path().is_dir() {
				langs.insert(entry.file_name().to_string_lossy().to_lowercase());
			}
		}
	}
	langs
}

/// The wxdragon-sys CMake build's locale output directory for the crate currently compiling.
fn wx_locale_dir() -> Option<PathBuf> {
	Some(target_profile_dir()?.join("wxdragon_sys_cmake_build").join("share").join("locale"))
}

/// The `target/<profile>` directory for the crate currently compiling, derived the same way
/// a `build.rs` would (`OUT_DIR` is `target/<profile>/build/<crate>-<hash>/out`).
fn target_profile_dir() -> Option<PathBuf> {
	let profile = env::var("PROFILE").ok()?;
	if let Ok(target_dir) = env::var("CARGO_TARGET_DIR") {
		let mut dir = PathBuf::from(target_dir);
		dir.push(profile);
		return Some(dir);
	}
	let out_dir = PathBuf::from(env::var("OUT_DIR").ok()?);
	out_dir.ancestors().nth(3).map(Path::to_path_buf)
}

/// Scan `locale_dir` for per-language `wxstd*.mo` catalogs, restricted to `app_langs`
/// (case-insensitively, so e.g. wx's `pt_BR` matches an app's `pt_br`).
fn matching_wx_catalogs(locale_dir: &Path, app_langs: &HashSet<String>) -> Vec<(String, PathBuf)> {
	let Ok(entries) = fs::read_dir(locale_dir) else {
		return Vec::new();
	};
	let mut lang_entries: Vec<_> = entries.flatten().collect();
	lang_entries.sort_by_key(std::fs::DirEntry::file_name);
	let mut catalogs = Vec::new();
	for entry in lang_entries {
		let lang = entry.file_name().to_string_lossy().to_string();
		if !app_langs.contains(&lang.to_lowercase()) {
			continue;
		}
		let lc_messages = entry.path().join("LC_MESSAGES");
		let Ok(files) = fs::read_dir(&lc_messages) else { continue };
		let mut mo_files: Vec<PathBuf> = files
			.flatten()
			.map(|f| f.path())
			.filter(|p| {
				p.extension().and_then(|e| e.to_str()) == Some("mo")
					&& p.file_stem().and_then(|s| s.to_str()).is_some_and(|s| s.starts_with("wxstd"))
			})
			.collect();
		mo_files.sort();
		if let Some(mo_path) = mo_files.into_iter().next() {
			catalogs.push((lang, mo_path));
		}
	}
	catalogs
}

#[cfg(test)]
mod tests {
	use super::*;

	/// A scratch directory under the system temp dir, removed on drop. Avoids pulling in a
	/// `tempfile` dependency for a handful of filesystem-fixture tests.
	struct ScratchDir(PathBuf);

	impl ScratchDir {
		fn new(name: &str) -> Self {
			let path = env::temp_dir().join(format!("patois_macros_test_{name}_{}", std::process::id()));
			let _ = fs::remove_dir_all(&path);
			fs::create_dir_all(&path).expect("create scratch dir");
			Self(path)
		}

		fn path(&self) -> &Path {
			&self.0
		}
	}

	impl Drop for ScratchDir {
		fn drop(&mut self) {
			let _ = fs::remove_dir_all(&self.0);
		}
	}

	fn write_mo(dir: &Path, lang: &str, filename: &str) {
		let lc_messages = dir.join(lang).join("LC_MESSAGES");
		fs::create_dir_all(&lc_messages).expect("create LC_MESSAGES dir");
		fs::write(lc_messages.join(filename), b"fake mo bytes").expect("write fake .mo file");
	}

	#[test]
	fn shipped_languages_lists_locale_subdirectories() {
		let scratch = ScratchDir::new("shipped_languages");
		let locale_dir = scratch.path().join("locale");
		fs::create_dir_all(locale_dir.join("de")).unwrap();
		fs::create_dir_all(locale_dir.join("pt_BR")).unwrap();
		// A stray file (not a directory) alongside real language dirs shouldn't be picked up.
		fs::write(locale_dir.join("README.md"), b"not a language").unwrap();
		let langs = shipped_languages(scratch.path());
		assert_eq!(langs, HashSet::from(["de".to_string(), "pt_br".to_string()]));
	}

	#[test]
	fn shipped_languages_empty_when_locale_dir_missing() {
		let scratch = ScratchDir::new("shipped_languages_missing");
		assert!(shipped_languages(scratch.path()).is_empty());
	}

	#[test]
	fn matching_wx_catalogs_filters_by_app_language_case_insensitively() {
		let scratch = ScratchDir::new("matching_catalogs");
		write_mo(scratch.path(), "de", "wxstd-3.3.mo");
		write_mo(scratch.path(), "pt_BR", "wxstd-3.3.mo");
		write_mo(scratch.path(), "af", "wxstd-3.3.mo");
		let app_langs = HashSet::from(["de".to_string(), "pt_br".to_string()]);
		let mut catalogs = matching_wx_catalogs(scratch.path(), &app_langs);
		catalogs.sort();
		assert_eq!(catalogs.len(), 2);
		assert_eq!(catalogs[0].0, "de");
		assert_eq!(catalogs[1].0, "pt_BR");
	}

	#[test]
	fn matching_wx_catalogs_picks_lowest_sorted_mo_when_multiple_present() {
		let scratch = ScratchDir::new("matching_catalogs_multi");
		write_mo(scratch.path(), "de", "wxstd-3.3.mo");
		write_mo(scratch.path(), "de", "wxstd-3.2.mo");
		let app_langs = HashSet::from(["de".to_string()]);
		let catalogs = matching_wx_catalogs(scratch.path(), &app_langs);
		assert_eq!(catalogs.len(), 1);
		assert!(catalogs[0].1.ends_with("wxstd-3.2.mo"));
	}

	#[test]
	fn matching_wx_catalogs_ignores_non_wxstd_mo_files() {
		let scratch = ScratchDir::new("matching_catalogs_ignore");
		write_mo(scratch.path(), "de", "somethingelse.mo");
		let app_langs = HashSet::from(["de".to_string()]);
		assert!(matching_wx_catalogs(scratch.path(), &app_langs).is_empty());
	}

	#[test]
	fn matching_wx_catalogs_empty_when_locale_dir_missing() {
		let scratch = ScratchDir::new("matching_catalogs_missing");
		let missing = scratch.path().join("does_not_exist");
		let app_langs = HashSet::from(["de".to_string()]);
		assert!(matching_wx_catalogs(&missing, &app_langs).is_empty());
	}
}
